domain: lab.shortrib.net
image_name: ubuntu-24.04-server-cloudimg-amd64.img
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
nameservers:
    primary: cooper
    secondaries:
        - maltman
        - stillman
    resolver_ips:
        - 10.105.0.252
        - 10.105.0.253
        - 10.105.0.254
    auth_ips:
        - 10.105.0.2
        - 10.105.0.3
        - 10.105.0.4
    management_ips:
        - 10.18.1.252
        - 10.18.1.253
        - 10.18.1.254
node:
    cpus: 1
    memory: 1024
    disk_size: 40
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:FZaE444Ck18Q1/3PcMMnYP5LgBSBia9bRR3Ful1B,iv:nf0IMgPskTPEpkkRYkCCFIF8orsS6k68k7CsTM95NAc=,tag:fcLJwuYtRKcpGGNiwOu2WA==,type:str]
    cluster: homelab
    storage_container: null
subnets:
    infra: infra
    management: management
octodns:
    allowed_ranges:
        - 10.105.0.0/24
        - 10.25.0.0/24
tls:
    # TODO: Add your SOPS-encrypted certificate, key, and CA
    cert: |
        -----BEGIN CERTIFICATE-----
        MIICiTCCAi+gAwIBAgIRAKLAURafu8NVVZ9lHNi4eKwwCgYIKoZIzj0EAwIwGzEZ
        MBcGA1UEAxMQU2hvcnRyaWIgTGFicyBFMTAeFw0yNjAxMDcxNTM5MTNaFw0yNjA0
        MDUwMzQwMTNaMB8xHTAbBgNVBAMTFGRucy5sYWIuc2hvcnRyaWIubmV0MFkwEwYH
        KoZIzj0CAQYIKoZIzj0DAQcDQgAEEgBXvml/FW5RJCxNgXywGXBhXfP0DVlAsi+F
        a/YjngCy872ZI4rirOd32XxeSIg6h+eNnTIS3+8PN3PiHusvMKOCAU4wggFKMA4G
        A1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYD
        VR0OBBYEFHGBOXHTv6H1sx36YwYkNRXFH3OQMB8GA1UdIwQYMBaAFBmLulkHJjhJ
        jppyFXB6ureii5uUMIGlBgNVHREEgZ0wgZqCFGRucy5sYWIuc2hvcnRyaWIubmV0
        ghdjb29wZXIubGFiLnNob3J0cmliLm5ldIIYbWFsdG1hbi5sYWIuc2hvcnRyaWIu
        bmV0ghlzdGlsbG1hbi5sYWIuc2hvcnRyaWIubmV0hwQKaQD8hwQKaQD9hwQKaQD/
        hwQKaQAChwQKaQADhwQKaQAEhwSsFGn8hwSsFGn9hwSsFGn+MDEGDCsGAQQBgqRk
        xihAAQQhMB8CAQIEBE9rdGEEFDBvYXh3bTMzbHFwbWlzbmRKNjk3MAoGCCqGSM49
        BAMCA0gAMEUCIQDvaZCaYX5jiQMRi47yGkjoSB/T9ayGkpQBYbM5C5BlYgIgcYME
        guiqCM7RWhZTwd4OU78lqA0+OJim86pczuveUgA=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIBoDCCAUagAwIBAgIRANESB11vABc8JTcWjREP86UwCgYIKoZIzj0EAwIwIDEe
        MBwGA1UEAxMVU2hvcnRyaWIgTGFicyBSb290IEUxMB4XDTIyMDUwNjAxMDc1MFoX
        DTMyMDUwMzAxMDc1MFowGzEZMBcGA1UEAxMQU2hvcnRyaWIgTGFicyBFMTBZMBMG
        ByqGSM49AgEGCCqGSM49AwEHA0IABDnlx0yPhEEKPUrx0yIOoBN5BvtHCy4RZwZU
        lpYxOwfS9gs1aCK3HHLqW131oXpxyKx0/4DndxrACO2H/SmN34yjZjBkMA4GA1Ud
        DwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQZi7pZByY4
        SY6achVwerq3ooublDAfBgNVHSMEGDAWgBTqqaMizGPTwqzmgziM1827/RDGFzAK
        BggqhkjOPQQDAgNIADBFAiAVum55I7kpg2k0IcuA451h9e+lrqE6G924OLTbAfr1
        bQIhAO5Ovbp9/CNrAwJ5kTytluNsX/YojErTal63yMZvqa21
        -----END CERTIFICATE-----
    key: ENC[AES256_GCM,data:HnGkR0EEjENMWWMZUQoka3f+cA+1znAx9dU6Usb0fSEsMm5jg4soRV89awDeafyvGlezR3dL+mWXNPe78Z2d8xOgOgaSihKHYLdGInCzwgswl/DoovMe0dYeHTFOF78hebc/kVamTWBNlliWntMLDkPbB3gO/4CPzH+F8ciN7ZchbkofjO42Ldey0ZAHxLJe5G4gPKJvKEWW23SXhph/wGPOJ6s+eU1BGP77Rm4qxz3/GjqPPszeEYhW2XyqXEgsAB7Lfcun5W8Cv7NT5SOopEv0VsT+ukmxqSx7MqKsGkfU5eQ=,iv:CaZsFsXBaH0orIy/vxMGHF1RB5MzylvD4C26HmuXlaI=,tag:2v7l0xZeFv5Yt7x2AIlQlA==,type:str]
    ca: |
        -----BEGIN CERTIFICATE-----
        MIIBpDCCAUqgAwIBAgIQMrjGbvdzyD63/WrEiob28DAKBggqhkjOPQQDAjAgMR4w
        HAYDVQQDExVTaG9ydHJpYiBMYWJzIFJvb3QgRTEwHhcNMjIwNTA2MDEwNzUwWhcN
        MzIwNTAzMDEwNzUwWjAgMR4wHAYDVQQDExVTaG9ydHJpYiBMYWJzIFJvb3QgRTEw
        WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASH3xjMX2xsnDZ7G0dxuVunoH7ZT4qO
        yNwQfYvMI/ZiuvNV8KyYLqrcD4cigiuVWmjvSAqT5TOkIcD8s10iWZSKo2YwZDAO
        BgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU6qmj
        Isxj08Ks5oM4jNfNu/0QxhcwHwYDVR0jBBgwFoAU6qmjIsxj08Ks5oM4jNfNu/0Q
        xhcwCgYIKoZIzj0EAwIDSAAwRQIgCs9bM8Ax8RnPuHZWrgZodf/vJ6dce7OFeOZr
        mdHeKP8CIQC/KLNuScd9FfpazDzAZYYPHR9vnDWCkYsJ+2NaiKdOew==
        -----END CERTIFICATE-----
tailscale:
    auth_key: tskey-auth-kVBjiSa5Xz11CNTRL-vHsH2LGUzM3zVzwdcytsS3ZefcRPdWNQ8
sops:
    lastmodified: "2026-01-08T14:13:31Z"
    mac: ENC[AES256_GCM,data:ecYENriUQZ4SgRHxdRlhriQ8HJX4EenwqujJnzoyufn/Dp5CW4dM+cq30kUztpOWq2KG3LZ6hpOFohLuAryX9Gs+u+Cts06kBSyGYxBTraPQMZM71bGf+AHVhQgpOrJr0HiQmZ2xJwsC7sJKnwjhJuNkCwso4Y3URCsq/kqfxJw=,iv:g31OH7evRIyDXLAwy8D++F6Mu/9RzR6NNqYxLTFxBTE=,tag:vkrZUO7rSh1oIMMUCT19vA==,type:str]
    pgp:
        - created_at: "2026-01-08T14:13:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAmRXXE3IC/bQawQ37qmP8zGgbCnuadU43ODSH4ZBTmjww
            fSTq0GSzgME8mRQnkLqL4awKTLmBpIQo8huP9xZuQwVcv/aY4dpzl34K9Go2i4at
            0l4BzHd+IvxEqjao8PjpuP68PSQ0DJQF69yxoMzvgHlIJ1V+yD9Wyj7fVD7wdkE6
            diqepqw/yjxNHQ1Q5tJ2pFzJG+ztNnUggik27xY5lFqo0HxdnwNY+hVvpMC9/Iad
            =GdF2
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret|key)$
    version: 3.11.0
