domain: lab.shortrib.net
image_name: ubuntu-24.04-server-cloudimg-amd64.img
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
nameservers:
    primary: cooper
    secondaries:
        - maltman
        - stillman
    resolver_ips:
        - 10.105.0.252
        - 10.105.0.253
        - 10.105.0.254
    resolver_macs:
        - 52:54:00:69:00:fc
        - 52:54:00:69:00:fd
        - 52:54:00:69:00:fe
    auth_ips:
        - 10.105.0.2
        - 10.105.0.3
        - 10.105.0.4
    auth_macs:
        - 52:54:00:69:00:02
        - 52:54:00:69:00:03
        - 52:54:00:69:00:04
node:
    cpus: 1
    memory: 1024
    disk_size: 40
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:PEqj/fEbcuClQHvtpAaLAmcVoDJjBZwtZNQDqyP/,iv:jeLuWrAxI9Lve31wZ5aoMhDgKeAuXkkbAD1exGqLzvM=,tag:RnUOh2Hyh1cO9sgbtexQKg==,type:str]
    cluster: homelab
    storage_container: null
subnets:
    infra:
        vlan_id: 105
        cidr: 10.105.0.0/16
        gateway: 10.105.0.1
        pool_start: 10.105.0.100
        pool_end: 10.105.0.250
    management:
        # TODO: Set your management VLAN ID
        vlan_id: null
        # TODO: Set CIDR (e.g., 10.100.0.0/16)
        cidr: null
        # TODO: Set gateway IP
        gateway: null
        # TODO: Set IPAM pool start
        pool_start: null
        # TODO: Set IPAM pool end
        pool_end: null
octodns:
    allowed_ranges:
        # TODO: Adjust to your OctoDNS host ranges
        - 10.105.0.0/24
tls:
    # TODO: Add your SOPS-encrypted certificate, key, and CA
    cert: |
        -----BEGIN CERTIFICATE-----
        YOUR_CERTIFICATE_HERE
        -----END CERTIFICATE-----
    key: |
        -----BEGIN PRIVATE KEY-----
        YOUR_PRIVATE_KEY_HERE
        -----END PRIVATE KEY-----
    ca: |
        -----BEGIN CERTIFICATE-----
        YOUR_CA_CERTIFICATE_HERE
        -----END CERTIFICATE-----
tailscale:
    auth_key: tskey-auth-kVBjiSa5Xz11CNTRL-vHsH2LGUzM3zVzwdcytsS3ZefcRPdWNQ8
sops:
    lastmodified: "2026-01-06T15:08:56Z"
    mac: ENC[AES256_GCM,data:2tq++ZVNoH3EveCZ1s/Gr7GYpxCw0GGi3Zk48ltqI0Vi0025+kG2KiebfJ+OWNtmg4bAVgqi4sdmSrsDrIX2/m/ieV7tdb8rVuL3t/WBGZqgk8dhhMqruWc3Kt3On+7kRSaACR1jL6xOTHNbl5aptx2WWwvOgVvVmjRi5Sschc0=,iv:X+P3LcsrPcxI5HDqD6IpftacPc0SiUvWktzRk99Ymw8=,tag:ddSXrmC2f1ct7Aao+btF7g==,type:str]
    pgp:
        - created_at: "2026-01-06T15:08:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA3CtBWtk1mgFFIMm1ZmAjiLTeiBvBb9tbASpJD3hlXUgw
            v3GxgMIQbcLoLFc3Oqm4k38PUMRgPGXeDpImXeLTkkj4R9TncJ5ss2STjNPLHKNw
            0lwBAy1HKTm05SmCmO0d6PIBYcM17Lvbn837qSQrrFOXXVT6+IyXlnSEPsp8NSP7
            NmpM7MCPhCMrQKd8qY9jHx+FmQi9fOk9n39+X6yfdf2pZaaxXUh+V7yJ4JP7iw==
            =Iqpr
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
